package files

import (
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Golden vector generated by the Python reference:
// f'{1790333971.837094}-17-{zlib.adler32(b"C:\\share\\hello.txt") & 0xFFFFFFFF}'
// (single backslashes; adler32 verified byte-exact).
func TestWerkzeugETagGolden(t *testing.T) {
	got := WerkzeugETag(`C:\share\hello.txt`, 1790333971.837094, 17)
	want := `"1790333971.837094-17-1056048875"`
	if got != want {
		t.Fatalf("etag = %s, want %s", got, want)
	}
}

func TestMtimeFloatMatchesGetmtime(t *testing.T) {
	// sec + rem/1e9 bit-identical to CPython os.path.getmtime (verified
	// against CPython 3.14 on Windows).
	mt := time.Unix(1790333971, 837094000)
	if got := mtimeFloat(mt); got != 1790333971.837094 {
		t.Fatalf("mtimeFloat = %.17g", got)
	}
}

func serveForTest(t *testing.T, abs string, headers map[string]string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(http.MethodGet, "/download/f.bin", nil)
	for k, v := range headers {
		req.Header.Set(k, v)
	}
	rec := httptest.NewRecorder()
	ServeFile(rec, req, abs, "f.bin")
	return rec
}

func fixtureForTest(t *testing.T, content []byte) string {
	t.Helper()
	abs := filepath.Join(t.TempDir(), "f.bin")
	if err := os.WriteFile(abs, content, 0o644); err != nil {
		t.Fatal(err)
	}
	return abs
}

func TestConditionalAndMultiRange(t *testing.T) {
	content := []byte("0123456789abcdef")
	abs := fixtureForTest(t, content)
	rec := serveForTest(t, abs, nil)
	if rec.Code != http.StatusOK {
		t.Fatalf("full = %d", rec.Code)
	}
	etag := rec.Header().Get("ETag")
	if !strings.HasPrefix(etag, `"`) || !strings.Contains(etag, "-") {
		t.Fatalf("etag shape = %q", etag)
	}

	// If-None-Match → 304 (weak form too).
	for _, inm := range []string{etag, "W/" + etag} {
		rec = serveForTest(t, abs, map[string]string{"If-None-Match": inm})
		if rec.Code != http.StatusNotModified {
			t.Errorf("inm %q = %d", inm, rec.Code)
		}
	}
	// If-Modified-Since in the future → 304.
	rec = serveForTest(t, abs, map[string]string{
		"If-Modified-Since": time.Now().Add(time.Hour).UTC().Format(http.TimeFormat),
	})
	if rec.Code != http.StatusNotModified {
		t.Errorf("ims = %d", rec.Code)
	}

	// Multi-range → 206 multipart.
	rec = serveForTest(t, abs, map[string]string{"Range": "bytes=0-3, 8-11"})
	if rec.Code != http.StatusPartialContent {
		t.Fatalf("multi = %d (%s)", rec.Code, rec.Body.String())
	}
	ct := rec.Header().Get("Content-Type")
	if !strings.HasPrefix(ct, "multipart/byteranges; boundary=") {
		t.Fatalf("multi ct = %q", ct)
	}
	body := rec.Body.String()
	if !strings.Contains(body, "bytes 0-3/16") || !strings.Contains(body, "bytes 8-11/16") {
		t.Fatalf("multi body = %q", body)
	}
	if !strings.Contains(body, "0123") || !strings.Contains(body, "89ab") {
		t.Fatalf("multi payload = %q", body)
	}

	// If-Range mismatch → full 200.
	rec = serveForTest(t, abs, map[string]string{
		"Range": "bytes=0-3", "If-Range": `"stale"`,
	})
	if rec.Code != http.StatusOK || rec.Body.String() != string(content) {
		t.Errorf("stale if-range = %d %q", rec.Code, rec.Body.String())
	}
	// If-Range match → 206.
	rec = serveForTest(t, abs, map[string]string{
		"Range": "bytes=0-3", "If-Range": etag,
	})
	if rec.Code != http.StatusPartialContent || rec.Body.String() != "0123" {
		t.Errorf("fresh if-range = %d %q", rec.Code, rec.Body.String())
	}
}
