package files

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
)

func loadStatic(t *testing.T) map[string]any {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	p := filepath.Join(filepath.Dir(file), "..", "..", "..", "tests", "fixtures", "go_migration", "milestone_c", "static_vectors.json")
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	var v map[string]any
	if err := json.Unmarshal(data, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

func TestExtensionSetsParity(t *testing.T) {
	v := loadStatic(t)
	sets := v["ext_sets"].(map[string]any)
	got := map[string][]string{
		"archive": ArchiveExtensions,
		"audio":   AudioExtensions,
		"image":   ImageExtensions,
		"text":    TextExtensions,
		"video":   VideoExtensions,
	}
	for cat, wantAny := range sets {
		var want []string
		for _, e := range wantAny.([]any) {
			want = append(want, e.(string))
		}
		have := append([]string{}, got[cat]...)
		sort.Strings(have)
		if strings.Join(have, ",") != strings.Join(want, ",") {
			t.Errorf("%s sets differ", cat)
		}
	}
	for _, c := range v["file_types"].([]any) {
		m := c.(map[string]any)
		if got := FileType(m["ext"].(string)); got != m["expect"].(string) {
			t.Errorf("FileType(%q) = %q, want %q", m["ext"], got, m["expect"])
		}
	}
}

func TestSafeFilenameVectors(t *testing.T) {
	v := loadStatic(t)
	for i, c := range v["safe_filenames"].([]any) {
		m := c.(map[string]any)
		if got := SafeFilename(m["inp"].(string)); got != m["out"].(string) {
			t.Errorf("case %d: SafeFilename(%q) = %q, want %q", i, m["inp"], got, m["out"])
		}
	}
}

func TestSafeFilenameNFCParity(t *testing.T) {
	// Expected outputs generated by unicodedata.normalize("NFC", ...) in Python.
	cases := []struct{ in, want string }{
		{"\u1100\u1161\u11b6.txt", "\uac0f.txt"},
		{"cafe\u0065\u0301.txt", "cafe\u00e9.txt"},
		{"\u0041\u030a.doc", "\u00c5.doc"},
		{"plain.txt", "plain.txt"},
	}
	for _, c := range cases {
		if got := SafeFilename(c.in); got != c.want {
			t.Errorf("SafeFilename(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestFmtBytesVectors(t *testing.T) {
	v := loadStatic(t)
	for i, c := range v["fmt_bytes"].([]any) {
		m := c.(map[string]any)
		if got := FmtBytes(int64(m["size"].(float64))); got != m["out"].(string) {
			t.Errorf("case %d: FmtBytes(%v) = %q, want %q", i, m["size"], got, m["out"])
		}
	}
}
