from collections.abc import Iterator, MutableMapping
from typing import Generic, TypeVar

_K = TypeVar("_K")
_V = TypeVar("_V")


class TTLCache(MutableMapping[_K, _V], Generic[_K, _V]):
    maxsize: int
    ttl: float

    def __init__(self, maxsize: int, ttl: float | int) -> None: ...
    def __getitem__(self, key: _K) -> _V: ...
    def __setitem__(self, key: _K, value: _V) -> None: ...
    def __delitem__(self, key: _K) -> None: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __len__(self) -> int: ...
